AIRTABLE_API_KEY = st.secrets["pat6XSPyurlmo8YVP.32cafea17af62fb72cdbb825a806668800aae1cf8f95551e961c52f791659c99"]
AIRTABLE_BASE_ID = st.secrets["appRBJiJBJ6FDAWr4"]
AIRTABLE_TABLE_NAME = "Employees"
OPENAI_API_KEY = st.secrets["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"]
openai.api_key = OPENAI_API_KEY
